site:
  build: .
  ports:
    - "9080:80"
  volumes:
    - ./src:/var/www/html/
  links:
    - database
php-myadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - "8080:80"
  environment:
    - MYSQL_USERNAME=andrea
    - MYSQL_PASSWORD=ciaone
  links:
    - database:mysql
database:
  image: mysql:5.5
  ports:
    - "3333:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=test
    - MYSQL_USER=andrea
    - MYSQL_PASSWORD=ciaone
  volumes:
    - ./data:/var/lib/mysql